version: "3"

services:
  nginx:
    container_name: app_nginx
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/project/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  php:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/var/www/project/
    networks:
      - app_network
    depends_on:
      - db

  db:
    container_name: app_db
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=localhost
      - POSTGRES_USER=localhost
      - POSTGRES_DB=symfony
    volumes:
      - ./database:/var/lib/postgres
    ports:
     - "5434:5432"
    networks:
      - app_network

  # db-test:
  #   container_name: app_db_test
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_USER=localhost
  #     - POSTGRES_DB=symfony-test
  #   volumes:
  #     - ./database-test:/var/lib/postgres
  #   ports:
  #    - "5435:5432"
  #   networks:
  #     - app_network

networks:
  app_network: 
