liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        # avatar:
        #     quality: 100
        #     cache: ~
        #     filters:
        #         thumbnail: { size: [100, 100], mode: outbound }
        post_thumbnail:
            quality: 100
            cache: ~
            filters:
                thumbnail:
                    size:          [290, 160]
                    mode:          outbound
                    allow_upscale: true
        avatar_minified:
            quality: 100
            cache: ~
            filters:
                thumbnail:
                    size:          [70, 70]
                    mode:          outbound
                    allow_downscale: true

        avatar_super_minified:
            quality: 100
            cache: ~
            filters:
                thumbnail:
                    size:          [45, 45]
                    mode:          outbound
                    allow_downscale: true

        avatar_full:
            quality: 100
            cache: ~
            filters:
                thumbnail:
                    size:          [150, 150]
                    mode:          outbound
                    allow_downscale: true
                    allow_upscale: true

