liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        # avatar:
        #     quality: 100
        #     cache: ~
        #     filters:
        #         thumbnail: { size: [100, 100], mode: outbound }
        post_thumbnail:
            quality: 100
            cache: ~
            filters:
                thumbnail:
                    size:          [290, 160]
                    mode:          outbound
                    allow_upscale: true